/**
 * Mlld Parser Entry Point
 * 
 * Provides the main parsing functionality for Mlld documents.
 * Re-exports the generated parser and related types.
 */

// Import the generated parser
// Note: This imports the ES module version generated by build-grammar.mjs
import parser from '../generated/parser/parser.js';
import { helpers as generatedHelpers } from '../generated/parser/grammar-core.js';
import type { GrammarWarning } from '../deps/grammar-core.js';

// Import types
import type { MlldMode, MlldNode } from '@core/types';

/**
 * Parser options
 */
export interface ParserOptions {
  /** Starting rule (default: 'Start') */
  startRule?: string;
  /** Parsing mode for strict vs markdown semantics */
  mode?: MlldMode;
  /** Additional options passed to PEG parser */
  [key: string]: any;
}

/**
 * Parser result
 */
export interface ParseResult {
  /** The parsed AST */
  ast: MlldNode[];
  /** Whether parsing succeeded */
  success: boolean;
  /** Error if parsing failed */
  error?: Error;
  /** Non-fatal grammar warnings */
  warnings: GrammarWarning[];
}

/**
 * Parse Mlld source code into an AST
 * 
 * @param source The Mlld source code to parse
 * @param options Parser options
 * @returns The parsed AST nodes
 * @throws {SyntaxError} If the source code is invalid
 */
export async function parse(source: string, options?: ParserOptions): Promise<ParseResult> {
  const warnings: GrammarWarning[] = [];
  generatedHelpers.setWarningCollector(warnings);

  try {
    const ast = parser.parse(source, {
      startRule: 'Start',
      mode: 'markdown',
      ...options
    });
    
    return {
      ast,
      success: true,
      warnings
    };
  } catch (error) {
    return {
      ast: [],
      success: false,
      error: error instanceof Error ? error : new Error(String(error)),
      warnings
    };
  } finally {
    generatedHelpers.clearWarningCollector();
  }
}

/**
 * Synchronous parse function for compatibility
 */
export function parseSync(source: string, options?: ParserOptions): MlldNode[] {
  const warnings: GrammarWarning[] = [];
  generatedHelpers.setWarningCollector(warnings);
  try {
    return parser.parse(source, {
      startRule: 'Start',
      mode: 'markdown',
      ...options
    });
  } finally {
    generatedHelpers.clearWarningCollector();
  }
}

// Re-export the parser and SyntaxError
export { parser };
export const SyntaxError = parser.SyntaxError;

// Export types
export type { MlldNode } from '@core/types';
