/**
 * Shared base types with no dependencies
 * 
 * This file is the foundation for breaking circular dependencies in the type system.
 * It contains only primitive types with no imports that other modules can safely depend on.
 * 
 * IMPORTANT: This file must NOT import from any other module to avoid circular dependencies.
 */

// Core node types that everything depends on
type NodeType = 
  | 'Directive'
  | 'Text'
  | 'CodeFence'
  | 'Comment'
  | 'Error'
  | 'VariableReference'
  | 'Variable';

// Position in a source file
interface Position {
  line: number;
  column: number;
}

// Location range in a source file
interface SourceLocation {
  start: Position;
  end: Position;
}

// Base node properties that all AST nodes share
interface BaseNode {
  type: NodeType;
  location?: SourceLocation;
}

// Directive kinds
type DirectiveKind = 
  | 'text'
  | 'data'
  | 'define'
  | 'import'
  | 'embed'
  | 'path'
  | 'run';

// Variable reference field types  
type FieldType = 'field' | 'index';

/**
 * Represents a single step (property access or index access) in a variable reference path.
 * This is the standard AST representation generated by the parser.
 */
interface Field {
  type: FieldType;
  value: string | number;
}

// Variable value types
type VariableType = 
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'array'
  | 'null'
  | 'undefined'
  | 'function'
  | 'symbol'
  | 'bigint';

// Format operators for variable formatting
type FormatOperator = 'json' | 'raw' | 'stringify';

// Special path variable constants
export const SPECIAL_PATH_VARS = {
  CURRENT_FILE: '$CURRENT_FILE',
  CURRENT_DIR: '$CURRENT_DIR',
  PROJECT_ROOT: '$PROJECT_ROOT'
};

// Environment variable prefix
export const ENV_VAR_PREFIX = 'ENV.';

// Variable patterns
export const VAR_PATTERNS = {
  VAR_START: '${',
  VAR_END: '}',
  BRACE_START: '{',
  BRACE_END: '}',
  FIELD_ACCESS: '.',
  INDEX_ACCESS_START: '[',
  INDEX_ACCESS_END: ']',
  FORMAT_OPERATOR: '|'
};

// Type-only exports for all types and interfaces
export type {
  NodeType,
  Position,
  SourceLocation,
  BaseNode,
  DirectiveKind,
  FieldType,
  Field,
  VariableType,
  FormatOperator
};