name: meld-typespec-variables-design
description: "Generates type specification for variable handling incorporating feedback from relevant services."
outputPath: output # Relative to workflow.yaml

files:
  # General Context
  architectureDocs:
    - ../../docs/dev/DI-ARCHITECTURE.md
    - ../../docs/dev/PIPELINE.md
  directiveClarityDoc: ../../_dev/VARIABLES-CLARITY.md

  # Component-Specific Files
  CoreDirectiveCode:
    - ../../services/pipeline/DirectiveService/DirectiveService.ts
    - ../../services/pipeline/DirectiveService/IDirectiveService.ts
    - ../../services/pipeline/DirectiveService/interfaces/DirectiveTypes.ts
  
  VariableHandlerCode:
    - ../../services/pipeline/ResolutionService/resolvers/VariableReferenceResolver.ts
    - ../../services/pipeline/ResolutionService/resolvers/types.ts
    - ../../services/pipeline/ResolutionService/resolvers/StringLiteralHandler.ts
  
  ParserCoreCode:
    - ../../services/pipeline/ParserService/ParserService.ts
    - ../../services/pipeline/ParserService/IParserService.ts
  
  InterpreterCoreCode:
    - ../../services/pipeline/InterpreterService/InterpreterService.ts
    - ../../services/pipeline/InterpreterService/IInterpreterService.ts
  
  ResolutionCoreCode:
    - ../../services/pipeline/ResolutionService/ResolutionService.ts
    - ../../services/pipeline/ResolutionService/IResolutionService.ts
  
  StateManagementCode:
    - ../../services/state/StateService/StateService.ts
    - ../../services/state/StateService/IStateService.ts
    - ../../services/state/StateService/types.ts
    - ../../services/state/utilities/StateVariableCopier.ts
  
  ContentResolutionCode:
    - ../../services/pipeline/ResolutionService/resolvers/ContentResolver.ts
    - ../../services/pipeline/ResolutionService/resolvers/StringLiteralHandler.ts
  
  FileSystemCoreCode:
    - ../../services/fs/FileSystemService/FileSystemService.ts
    - ../../services/fs/FileSystemService/IFileSystemService.ts

global_variables:
  overallArchitecture: "{{ files.architectureDocs }}"
  directiveName: "variables"
  directiveClarityContent: "{{ files.directiveClarityDoc }}"

iterable_objects:
  services:
    CoreDirective:
      description: "Core directive handling and type definitions"
      codeContent: "{{ files.CoreDirectiveCode }}"
    
    VariableHandler:
      description: "Variable resolution and handling"
      codeContent: "{{ files.VariableHandlerCode }}"
    
    ParserCore:
      description: "Core parsing functionality for directives"
      codeContent: "{{ files.ParserCoreCode }}"
    
    InterpreterCore:
      description: "Core interpretation pipeline orchestration"
      codeContent: "{{ files.InterpreterCoreCode }}"
    
    ResolutionCore:
      description: "Core resolution service functionality"
      codeContent: "{{ files.ResolutionCoreCode }}"
    
    StateManagement:
      description: "State management and variable storage"
      codeContent: "{{ files.StateManagementCode }}"
    
    ContentResolution:
      description: "Content and string literal resolution"
      codeContent: "{{ files.ContentResolutionCode }}"
    
    FileSystemCore:
      description: "Core filesystem operations"
      codeContent: "{{ files.FileSystemCoreCode }}"

sets:
  # Sequence with added grouping set:
  - useSet: gather-requirements
  - useSet: group-requirements     # NEW: Group synthesis step
  - useSet: synthesize-requirements # Now consolidates grouped outputs
  - useSet: draft-spec
  - useSet: collect-draft-feedback
  - useSet: refine-spec 