#!/usr/bin/env node

/**
 * Generate version.ts file with the current package version
 * This is run during the build process to embed the version
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Get the directory of this script
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read package.json from the script's location (project root)
const packageJsonPath = join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));

// Generate the version.ts content
const versionContent = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const version = '${packageJson.version}';
`;

// Write to core/version.ts
const versionPath = join(__dirname, '..', 'core', 'version.ts');
writeFileSync(versionPath, versionContent);

console.log(`Generated version.ts with version ${packageJson.version}`);