name: Deploy Docs

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/docs.yml'

# Add permissions configuration here
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: website/package-lock.json

      - name: Install Dependencies
        working-directory: website
        run: npm ci

      - name: Build
        working-directory: website
        run: npm run build

      - name: Create .nojekyll file
        run: touch website/_site/.nojekyll
        
      # Add CNAME file for custom domain
      - name: Create CNAME file
        run: echo "meld.ai" > website/_site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/_site
          publish_branch: gh-pages
          force_orphan: true  # Create a fresh deployment without commit history
