name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build grammar (required for linting)
      run: npm run build:grammar
    
    - name: Run ESLint
      run: npm run lint
      continue-on-error: false # Fail the build on any ESLint errors
    
    - name: Check for AST violations
      run: |
        echo "Checking for AST-specific rule violations..."
        npm run lint 2>&1 | grep -E "(no-raw-field-access|no-ast-string-manipulation|require-ast-type-guards)" || echo "No AST violations found ✓"
      if: always() # Run even if previous step failed