name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build grammar (required before tests)
      run: npm run build
    
    - name: Run tests
      run: npm test
      # Note: Token edge case tests are excluded from main test suite
      # Run locally with: npm run test:tokens
    
    - name: Run test coverage
      run: npm run test:coverage
      if: matrix.node-version == '20'
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.node-version == '20'
      with:
        fail_ci_if_error: false
