name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build grammar (required before tests)
      run: npm run build

    - name: Run tests
      run: npm test
      # Note: Token edge case tests are excluded from main test suite
      # Run locally with: npm run test:tokens

    - name: Run test coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
